import path from 'node:path';
import { config as dotenv } from 'dotenv';
import { storagePaths, applicationPaths } from '../../desktop/storage-paths.mjs';
dotenv({ path: process.env.FROK_ENV_FILE || ['.env.local', '.env'], quiet: true });
export const root = path.resolve(/* turbopackIgnore: true */ process.env.FROK_APP_ROOT || process.cwd());
const storage = storagePaths(process.env, { root });
export const pipelineHome = storage.pipelineHome;
export const pipelineStateDirectory = path.resolve(root, process.env.FROK_PIPELINE_STATE_DIR || applicationPaths({ ...process.env, FROK_HOME: pipelineHome }, { root }).state);
export const defaultPipelinesDir = path.join(pipelineHome,'pipelines');
export const pipelineTemplatesDir = path.join(root,'resources','pipelines');
export const dataDir = storage.data;
